using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

[Table("Games")]
public class Game
{
    [Key]
    public int GameID { get; set; }
    public string Name { get; set; } = string.Empty;
    public string Type { get; set; } = string.Empty;
    public float Cost { get; set; }

    // Initialize an empty collection
    // this is for the relationship with Play (as per the suggestion of copilot)
    public ICollection<Play> Plays { get; set; } = new List<Play>();
}
//classes were generated by using Claude and then slightly modified